name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: musl cross-compiler download
      run: wget https://musl.cc/aarch64-linux-musl-cross.tgz

    - name: musl unzip
      run: tar -zxf aarch64-linux-musl-cross.tgz -c /usr/

    - uses: ./
      with:
          name: "musl"
          url: "https://musl.cc/aarch64-linux-musl-cross.tgz"
          pathInArchive: "/usr/"

    - name: add to PATH
      run: echo "/usr/bin/aarch64-linux-musl-cross/bin/" >> $GITHUB_PATH
          
    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Configure CMake
      run: CC=aarch64-linux-musl-gcc CXX=aarch64-linux-musl-g++ cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: CC=aarch64-linux-musl-gcc CXX=aarch64-linux-musl-g++ cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
