name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: musl cross-compiler
      uses: Lesmiscore/musl-cross-compilers@v0.5
      with:
        target: aarch64-linux-musl
          
    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Configure CMake
      run: CC=aarch64-linux-musl-gcc CXX=aarch64-linux-musl-g++ cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -E env 

    - name: Build
      run: CC=aarch64-linux-musl-gcc CXX=aarch64-linux-musl-g++ cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
